// Every `name` value in public/map/cebu-boundaries.geojson. Kept as a fixed
// list (rather than fetched client-side) so the admin publish form can only
// pick a name that Locate Me's point-in-polygon matching (findContainingFeature)
// will actually recognize — a typo here would silently break matching.
export const CEBU_MUNICIPALITIES = [
  "Alcantara",
  "Alcoy",
  "Alegria",
  "Aloguinsan",
  "Argao",
  "Asturias",
  "Badian",
  "Balamban",
  "Bantayan",
  "Barili",
  "City of Bogo",
  "Boljoon",
  "Borbon",
  "City of Carcar",
  "Carmen",
  "Catmon",
  "Compostela",
  "Consolacion",
  "Cordova",
  "Daanbantayan",
  "Dalaguete",
  "Danao City",
  "Dumanjug",
  "Ginatilan",
  "Liloan",
  "Madridejos",
  "Malabuyoc",
  "Medellin",
  "Minglanilla",
  "Moalboal",
  "City of Naga",
  "Oslob",
  "Pilar",
  "Pinamungajan",
  "Poro",
  "Ronda",
  "Samboan",
  "San Fernando",
  "San Francisco",
  "San Remigio",
  "Santa Fe",
  "Santander",
  "Sibonga",
  "Sogod",
  "Tabogon",
  "Tabuelan",
  "City of Talisay",
  "City of Toledo",
  "Tuburan",
  "Tudela",
  "Cebu City",
  "Lapu-Lapu City",
  "Mandaue City",
] as const;
